@startuml

package presentation{
	class Main{
	
	}
	
	class MainView{}
	
	class UMLViewer{}
	
}

package domain{

	class Compiler{
	
	}
	
	abstract class MyClass{
	
	}
	
	abstract class MyMethod{
	
	}
	
	abstract class MyField{
	
	}
	
	abstract class Check{
		+{abstract}test(p:Project):String
		+{abstract}getName():String
	}
	
}

package data{
	class Reader{
	
	}
}

MyClass-->"*"MyMethod
MyClass-->"*"MyField
MainView-->Compiler


@enduml